# Schema for configuration files of the Form Mode Manager module.
form_mode_manager.settings:
  type: config_object
  label: 'Form Mode Manager common settings'
  mapping:
    form_modes:
      type: sequence
      label: 'Form mode to exclude of manager system'
      sequence:
        type: mapping
        mapping:
          to_exclude:
            type: sequence
            label: 'List of form-mode to exclude'
            sequence:
              type: string
              label: Form mode name

form_mode_manager.links:
  type: config_object
  label: 'Links position'
  mapping:
    local_tasks:
      type: sequence
      label: 'Local tasks position by entity type'
      sequence:
        type: mapping
        label: 'Position of generated tasks by Form Mode Manager'
        mapping:
          position:
            type: string
            label: Position
